Patches, kernel configuration and build system adaptations (thanks to sakaki's work)
- Kernel configurations taken from sakaki gentoo kernel with minor changes
- Patches adapted for new kernel version
- uImage build quirks added from bot b2 and b3, again taken from sakaki's buildkernel scripts
- Minor changes in debian/rules

diff --git a/debian/patches/0002-remove-debian-packaging.patch b/debian/patches/0002-remove-debian-packaging.patch
--- a/debian/patches/0002-remove-debian-packaging.patch
+++ b/debian/patches/0002-remove-debian-packaging.patch
@@ -1,6 +1,42 @@
+--- a/scripts/package/Makefile
++++ b/scripts/package/Makefile
+@@ -66,33 +66,6 @@
+ 		$(UTS_MACHINE) -bb $(objtree)/binkernel.spec
+ 	rm binkernel.spec
+ 
+-# Deb target
+-# ---------------------------------------------------------------------------
+-quiet_cmd_builddeb = BUILDDEB
+-      cmd_builddeb = set -e; \
+-	test `id -u` = 0 || \
+-	test -n "$(KBUILD_PKG_ROOTCMD)" || { \
+-		which fakeroot >/dev/null 2>&1 && \
+-		KBUILD_PKG_ROOTCMD="fakeroot -u"; \
+-	} || { \
+-		echo; \
+-		echo "builddeb must be run as root (or using fakeroot)."; \
+-		echo "KBUILD_PKG_ROOTCMD is unset and fakeroot not found."; \
+-		echo "Try setting KBUILD_PKG_ROOTCMD to a command to acquire"; \
+-		echo "root privileges (e.g., 'fakeroot -u' or 'sudo')."; \
+-		false; \
+-	} && \
+-	\
+-	$$KBUILD_PKG_ROOTCMD $(CONFIG_SHELL) \
+-		$(srctree)/scripts/package/builddeb
+-
+-deb-pkg: FORCE
+-	$(MAKE) KBUILD_SRC=
+-	$(call cmd,builddeb)
+-
+-clean-dirs += $(objtree)/debian/
+-
+-
+ # tarball targets
+ # ---------------------------------------------------------------------------
+ tar%pkg: FORCE
 --- a/scripts/package/builddeb
 +++ /dev/null
-@@ -1,293 +0,0 @@
+@@ -1,375 +0,0 @@
 -#!/bin/sh
 -#
 -# builddeb 1.3
@@ -38,13 +74,15 @@
 -	sparc*)
 -		debarch=sparc ;;
 -	s390*)
--		debarch=s390 ;;
+-		debarch=s390$(grep -q CONFIG_64BIT=y $KCONFIG_CONFIG && echo x || true) ;;
 -	ppc*)
--		debarch=powerpc ;;
+-		debarch=$(grep -q CPU_LITTLE_ENDIAN=y $KCONFIG_CONFIG && echo ppc64el || echo powerpc) ;;
 -	parisc*)
 -		debarch=hppa ;;
 -	mips*)
 -		debarch=mips$(grep -q CPU_LITTLE_ENDIAN=y $KCONFIG_CONFIG && echo el || true) ;;
+-	arm64)
+-		debarch=arm64 ;;
 -	arm*)
 -		debarch=arm$(grep -q CONFIG_AEABI=y $KCONFIG_CONFIG && echo el || true) ;;
 -	*)
@@ -65,7 +103,7 @@
 -	fi
 -
 -	# Create the package
--	dpkg-gencontrol -isp $forcearch -Vkernel:debarch="${debarch:-$(dpkg --print-architecture)}" -p$pname -P"$pdir"
+-	dpkg-gencontrol $forcearch -Vkernel:debarch="${debarch:-$(dpkg --print-architecture)}" -p$pname -P"$pdir"
 -	dpkg --build "$pdir" ..
 -}
 -
@@ -81,27 +119,50 @@
 -fwdir="$objtree/debian/fwtmp"
 -kernel_headers_dir="$objtree/debian/hdrtmp"
 -libc_headers_dir="$objtree/debian/headertmp"
+-dbg_dir="$objtree/debian/dbgtmp"
 -packagename=linux-image-$version
--fwpackagename=linux-firmware-image
+-fwpackagename=linux-firmware-image-$version
 -kernel_headers_packagename=linux-headers-$version
 -libc_headers_packagename=linux-libc-dev
+-dbg_packagename=$packagename-dbg
 -
 -if [ "$ARCH" = "um" ] ; then
 -	packagename=user-mode-linux-$version
 -fi
 -
+-# Not all arches have the same installed path in debian
+-# XXX: have each arch Makefile export a variable of the canonical image install
+-# path instead
+-case $ARCH in
+-um)
+-	installed_image_path="usr/bin/linux-$version"
+-	;;
+-parisc|mips|powerpc)
+-	installed_image_path="boot/vmlinux-$version"
+-	;;
+-*)
+-	installed_image_path="boot/vmlinuz-$version"
+-esac
+-
+-BUILD_DEBUG="$(grep -s '^CONFIG_DEBUG_INFO=y' $KCONFIG_CONFIG || true)"
+-
 -# Setup the directory structure
--rm -rf "$tmpdir" "$fwdir" "$kernel_headers_dir" "$libc_headers_dir"
+-rm -rf "$tmpdir" "$fwdir" "$kernel_headers_dir" "$libc_headers_dir" "$dbg_dir"
 -mkdir -m 755 -p "$tmpdir/DEBIAN"
 -mkdir -p  "$tmpdir/lib" "$tmpdir/boot" "$tmpdir/usr/share/doc/$packagename"
 -mkdir -m 755 -p "$fwdir/DEBIAN"
--mkdir -p "$fwdir/lib" "$fwdir/usr/share/doc/$fwpackagename"
+-mkdir -p "$fwdir/lib/firmware/$version/" "$fwdir/usr/share/doc/$fwpackagename"
 -mkdir -m 755 -p "$libc_headers_dir/DEBIAN"
 -mkdir -p "$libc_headers_dir/usr/share/doc/$libc_headers_packagename"
 -mkdir -m 755 -p "$kernel_headers_dir/DEBIAN"
 -mkdir -p "$kernel_headers_dir/usr/share/doc/$kernel_headers_packagename"
+-mkdir -p "$kernel_headers_dir/lib/modules/$version/"
 -if [ "$ARCH" = "um" ] ; then
 -	mkdir -p "$tmpdir/usr/lib/uml/modules/$version" "$tmpdir/usr/bin"
+-fi
+-if [ -n "$BUILD_DEBUG" ] ; then
+-	mkdir -p "$dbg_dir/usr/share/doc/$dbg_packagename"
+-	mkdir -m 755 -p "$dbg_dir/DEBIAN"
 -fi
 -
 -# Build and install the kernel
@@ -110,33 +171,55 @@
 -	cp System.map "$tmpdir/usr/lib/uml/modules/$version/System.map"
 -	cp $KCONFIG_CONFIG "$tmpdir/usr/share/doc/$packagename/config"
 -	gzip "$tmpdir/usr/share/doc/$packagename/config"
--	cp $KBUILD_IMAGE "$tmpdir/usr/bin/linux-$version"
--else 
+-else
 -	cp System.map "$tmpdir/boot/System.map-$version"
 -	cp $KCONFIG_CONFIG "$tmpdir/boot/config-$version"
--	# Not all arches include the boot path in KBUILD_IMAGE
--	if [ -e $KBUILD_IMAGE ]; then
--		cp $KBUILD_IMAGE "$tmpdir/boot/vmlinuz-$version"
--	else
--		cp arch/$ARCH/boot/$KBUILD_IMAGE "$tmpdir/boot/vmlinuz-$version"
--	fi
+-fi
+-# Not all arches include the boot path in KBUILD_IMAGE
+-if [ -e $KBUILD_IMAGE ]; then
+-	cp $KBUILD_IMAGE "$tmpdir/$installed_image_path"
+-else
+-	cp arch/$ARCH/boot/$KBUILD_IMAGE "$tmpdir/$installed_image_path"
 -fi
 -
 -if grep -q '^CONFIG_MODULES=y' $KCONFIG_CONFIG ; then
--	INSTALL_MOD_PATH="$tmpdir" make KBUILD_SRC= modules_install
+-	INSTALL_MOD_PATH="$tmpdir" $MAKE KBUILD_SRC= modules_install
+-	rm -f "$tmpdir/lib/modules/$version/build"
+-	rm -f "$tmpdir/lib/modules/$version/source"
 -	if [ "$ARCH" = "um" ] ; then
 -		mv "$tmpdir/lib/modules/$version"/* "$tmpdir/usr/lib/uml/modules/$version/"
 -		rmdir "$tmpdir/lib/modules/$version"
 -	fi
+-	if [ -n "$BUILD_DEBUG" ] ; then
+-		for module in $(find $tmpdir/lib/modules/ -name *.ko -printf '%P\n'); do
+-			module=lib/modules/$module
+-			mkdir -p $(dirname $dbg_dir/usr/lib/debug/$module)
+-			# only keep debug symbols in the debug file
+-			$OBJCOPY --only-keep-debug $tmpdir/$module $dbg_dir/usr/lib/debug/$module
+-			# strip original module from debug symbols
+-			$OBJCOPY --strip-debug $tmpdir/$module
+-			# then add a link to those
+-			$OBJCOPY --add-gnu-debuglink=$dbg_dir/usr/lib/debug/$module $tmpdir/$module
+-		done
+-	fi
 -fi
 -
--make headers_check
--make headers_install INSTALL_HDR_PATH="$libc_headers_dir/usr"
+-if [ "$ARCH" != "um" ]; then
+-	$MAKE headers_check KBUILD_SRC=
+-	$MAKE headers_install KBUILD_SRC= INSTALL_HDR_PATH="$libc_headers_dir/usr"
+-fi
 -
 -# Install the maintainer scripts
 -# Note: hook scripts under /etc/kernel are also executed by official Debian
--# kernel packages, as well as kernel packages built using make-kpkg
+-# kernel packages, as well as kernel packages built using make-kpkg.
+-# make-kpkg sets $INITRD to indicate whether an initramfs is wanted, and
+-# so do we; recent versions of dracut and initramfs-tools will obey this.
 -debhookdir=${KDEB_HOOKDIR:-/etc/kernel}
+-if grep -q '^CONFIG_BLK_DEV_INITRD=y' $KCONFIG_CONFIG; then
+-	want_initrd=Yes
+-else
+-	want_initrd=No
+-fi
 -for script in postinst postrm preinst prerm ; do
 -	mkdir -p "$tmpdir$debhookdir/$script.d"
 -	cat <<EOF > "$tmpdir/DEBIAN/$script"
@@ -147,7 +230,10 @@
 -# Pass maintainer script parameters to hook scripts
 -export DEB_MAINT_PARAMS="\$*"
 -
--test -d $debhookdir/$script.d && run-parts --arg="$version" $debhookdir/$script.d
+-# Tell initramfs builder whether it's wanted
+-export INITRD=$want_initrd
+-
+-test -d $debhookdir/$script.d && run-parts --arg="$version" --arg="/$installed_image_path" $debhookdir/$script.d
 -exit 0
 -EOF
 -	chmod 755 "$tmpdir/DEBIAN/$script"
@@ -240,15 +326,18 @@
 -
 -fi
 -
--# Build header package
--(cd $srctree; find . -name Makefile -o -name Kconfig\* -o -name \*.pl > "$objtree/debian/hdrsrcfiles")
--(cd $srctree; find arch/$SRCARCH/include include scripts -type f >> "$objtree/debian/hdrsrcfiles")
--(cd $objtree; find Module.symvers include scripts -type f >> "$objtree/debian/hdrobjfiles")
+-# Build kernel header package
+-(cd $srctree; find . -name Makefile\* -o -name Kconfig\* -o -name \*.pl) > "$objtree/debian/hdrsrcfiles"
+-(cd $srctree; find arch/$SRCARCH/include include scripts -type f) >> "$objtree/debian/hdrsrcfiles"
+-(cd $srctree; find arch/$SRCARCH -name module.lds -o -name Kbuild.platforms -o -name Platform) >> "$objtree/debian/hdrsrcfiles"
+-(cd $srctree; find $(find arch/$SRCARCH -name include -o -name scripts -type d) -type f) >> "$objtree/debian/hdrsrcfiles"
+-(cd $objtree; find arch/$SRCARCH/include Module.symvers include scripts -type f) >> "$objtree/debian/hdrobjfiles"
 -destdir=$kernel_headers_dir/usr/src/linux-headers-$version
 -mkdir -p "$destdir"
--(cd $srctree; tar -c -f - -T "$objtree/debian/hdrsrcfiles") | (cd $destdir; tar -xf -)
--(cd $objtree; tar -c -f - -T "$objtree/debian/hdrobjfiles") | (cd $destdir; tar -xf -)
+-(cd $srctree; tar -c -f - -T -) < "$objtree/debian/hdrsrcfiles" | (cd $destdir; tar -xf -)
+-(cd $objtree; tar -c -f - -T -) < "$objtree/debian/hdrobjfiles" | (cd $destdir; tar -xf -)
 -(cd $objtree; cp $KCONFIG_CONFIG $destdir/.config) # copy .config manually to be where it's expected to be
+-ln -sf "/usr/src/linux-headers-$version" "$kernel_headers_dir/lib/modules/$version/build"
 -rm -f "$objtree/debian/hdrsrcfiles" "$objtree/debian/hdrobjfiles"
 -
 -cat <<EOF >> debian/control
@@ -262,11 +351,10 @@
 - This is useful for people who need to build external modules
 -EOF
 -
--create_package "$kernel_headers_packagename" "$kernel_headers_dir"
--
 -# Do we have firmware? Move it out of the way and build it into a package.
 -if [ -e "$tmpdir/lib/firmware" ]; then
--	mv "$tmpdir/lib/firmware" "$fwdir/lib/"
+-	mv "$tmpdir/lib/firmware"/* "$fwdir/lib/firmware/$version/"
+-	rmdir "$tmpdir/lib/firmware"
 -
 -	cat <<EOF >> debian/control
 -
@@ -290,43 +378,37 @@
 - are used by the installed headers for GNU glibc and other system libraries.
 -EOF
 -
--create_package "$libc_headers_packagename" "$libc_headers_dir"
+-if [ "$ARCH" != "um" ]; then
+-	create_package "$kernel_headers_packagename" "$kernel_headers_dir"
+-	create_package "$libc_headers_packagename" "$libc_headers_dir"
+-fi
+-
 -create_package "$packagename" "$tmpdir"
 -
+-if [ -n "$BUILD_DEBUG" ] ; then
+-	# Build debug package
+-	# Different tools want the image in different locations
+-	# perf
+-	mkdir -p $dbg_dir/usr/lib/debug/lib/modules/$version/
+-	cp vmlinux $dbg_dir/usr/lib/debug/lib/modules/$version/
+-	# systemtap
+-	mkdir -p $dbg_dir/usr/lib/debug/boot/
+-	ln -s ../lib/modules/$version/vmlinux $dbg_dir/usr/lib/debug/boot/vmlinux-$version
+-	# kdump-tools
+-	ln -s lib/modules/$version/vmlinux $dbg_dir/usr/lib/debug/vmlinux-$version
+-
+-	cat <<EOF >> debian/control
+-
+-Package: $dbg_packagename
+-Section: debug
+-Provides: linux-debug, linux-debug-$version
+-Architecture: any
+-Description: Linux kernel debugging symbols for $version
+- This package will come in handy if you need to debug the kernel. It provides
+- all the necessary debug symbols for the kernel and its modules.
+-EOF
+-
+-	create_package "$dbg_packagename" "$dbg_dir"
+-fi
+-
 -exit 0
---- a/scripts/package/Makefile
-+++ b/scripts/package/Makefile
-@@ -75,33 +75,6 @@
- 
- clean-files += $(objtree)/binkernel.spec
- 
--# Deb target
--# ---------------------------------------------------------------------------
--quiet_cmd_builddeb = BUILDDEB
--      cmd_builddeb = set -e; \
--	test `id -u` = 0 || \
--	test -n "$(KBUILD_PKG_ROOTCMD)" || { \
--		which fakeroot >/dev/null 2>&1 && \
--		KBUILD_PKG_ROOTCMD="fakeroot -u"; \
--	} || { \
--		echo; \
--		echo "builddeb must be run as root (or using fakeroot)."; \
--		echo "KBUILD_PKG_ROOTCMD is unset and fakeroot not found."; \
--		echo "Try setting KBUILD_PKG_ROOTCMD to a command to acquire"; \
--		echo "root privileges (e.g., 'fakeroot -u' or 'sudo')."; \
--		false; \
--	} && \
--	\
--	$$KBUILD_PKG_ROOTCMD $(CONFIG_SHELL) \
--		$(srctree)/scripts/package/builddeb
--
--deb-pkg: FORCE
--	$(MAKE) KBUILD_SRC=
--	$(call cmd,builddeb)
--
--clean-dirs += $(objtree)/debian/
--
--
- # tarball targets
- # ---------------------------------------------------------------------------
- tar%pkg: FORCE
